function TEC(A1,VAl1,beta1,Rc1,Re1,Rb11,Rb21,Rl1,f1,Ie1,val1,N,r,s,q,y,b,def1)

Fig=figure('Name','Tranzistor Bipolar-Emitor-Comun',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.85 0.75],...
    'NumberTitle','off',...
    'Color',"#EDB120");



VAl=VAl1;               %-----------tensiunea continua de intrare----------
beta=beta1;             %-----------factorul de amplificare in curent------
Rc=Rc1;                 %-----------rezitenta din colector a TB------------
Re=Re1;                 %-----------rezistena din emitor a TB--------------
Rb1=Rb11;               %-----------rezistena 1 din baza a TB--------------
Rb2=Rb21;               %-----------rezistena 2 din baza a TB--------------
Rl=Rl1;                 %-----------rezistena load a TB--------------------
f=f1;                   %-----------frecventa------------------------------
A=A1;                   %-----------amplitudinea semnalului de intrare-----
Ie=Ie1;                 %-----------curentul din emitor--------------------
T=1/f;
t=0:T/100:N*T;
valoare=val1;           %-----------prestabilire a semnalului sinusoidal---
Ic=Ie1;                 %-----------Ie = Ic+Ib = beta*Ib+Ib = Ib*(beta+1) ≈ Ib*beta = Ic
def=def1;



%-----------parametrii de semnal mic 
gm=40*Ic;                  %-----------------transconductanta diferentiala
rbe=beta./gm;               %rezistenta interna de pe conexiunea Baza-Emitor



%-----------parametrii EC
Av=-gm*(Rc1*Rl)./(Rc1+Rl);                      %------amplificarea in tensiune
Ri=(Rb1*Rb2*rbe)/(Rb2*rbe+Rb1*rbe+Rb1*Rb2);     %---------rezistenta de intrare
Ro=Rc1;                                           %----------rezistenta de iesire
VO= VAl1-(Ic*Rc1);



%-----------buton pentru tipuri semnale
Tip_Semnal=uibuttongroup('Visible','on',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'Title','Tipul de semnal si reprezentare',...
'FontSize',15.5,...
'FontWeight','bold',...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.01 0.8 0.25 0.15]);

uicontrol('Style','popupmenu',...
'BackgroundColor','#FFFF00',...
'Units','normalized',...
'FontWeight','bold',...
'FontSize',12,...
'Position',[0 0.5 1 0.5],...
'value',valoare,...
'String','Sinusoidal|Triunghiular|Dreptunghiular|Dinte de fierestrau',...
'Callback','valoare=get(gco,''value''),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Tip_Semnal);



%-----------butoanele pentru parametrii

Butoane_parametrii=uibuttongroup('Visible','on',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'Title','Parametrii de intrare',...
'FontSize',20,...
'FontWeight','bold',...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.27 0.49 0.25 0.5]);

%-----------buton pentru tensiunea continua a circuitului
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.9 0.3 0.1],...
'String','VAl [V]',...
'FontSize',12,...
'FontWeight','bold',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.9 0.3 0.1],...
'String',VAl,...
'Parent',Butoane_parametrii,...
'Callback','VAl=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);');

%-----------buton pentru amplitudinea semnalului de intrare
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'FontWeight','bold',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontSize',12,...
'Position',[0.1 0.8 0.3 0.1],...
'String','A [V]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.8 0.3 0.1],...
'String',A,...
'Parent',Butoane_parametrii,...
'Callback','A=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);');





uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'FontWeight','bold',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontSize',12,...
'Position',[0.02 0.2 0.2 0.3],...
'String','ϕ(°)',...
'Parent',Tip_Semnal);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.18 0.2 0.3 0.3],...
'String',def,...
'Parent',Tip_Semnal,...
'Callback','def=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);');

%-----------buton pentru beta
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'FontSize',12,...
'FontWeight','bold',...
'HorizontalAlignment','center',...
'Position',[0.1 0.7 0.3 0.1],...
'String','Beta',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.7 0.3 0.1],...
'String',beta,...
'Callback','beta=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta din colector
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontWeight','bold',...
'Position',[0.1 0.6 0.3 0.1],...
'String','Rc[kOhm]',...
'FontSize',12,...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'String',Rc,...
'Position',[0.5 0.6 0.3 0.1],...
'Callback','Rc=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta din emitor
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontWeight','bold',...
'Position',[0.1 0.5 0.3 0.1],...
'String','Re [kOhm]',...
'FontSize',12,...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.5 0.3 0.1],...
'String',Re,...
'Callback','Re=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta 1 din baza
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontWeight','bold',...
'FontSize',12,...
'Position',[0.1 0.4 0.3 0.1],...
'String','Rb1 [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.4 0.3 0.1],...
'String',Rb1,...
'Callback','Rb1=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta 2 din baza
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontSize',12,...
'Position',[0.1 0.3 0.3 0.1],...
'String','Rb2 [kOhm]',...
'FontWeight','bold',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.3 0.3 0.1],...
'String',Rb2,...
'Callback','Rb2=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta load
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'FontWeight','bold',...
'HorizontalAlignment','center',...
'Position',[0.1 0.2 0.3 0.1],...
'FontSize',12,...
'String','Rl [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.2 0.3 0.1],...
'String',Rl,...
'Callback','Rl=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru frecventa
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'FontWeight','bold',...
'FontSize',12,...
'HorizontalAlignment','center',...
'Position',[0.1 0.1 0.3 0.1],...
'String','f [Hz]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.1 0.3 0.1],...
'String',f,...
'Callback','f=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);

%-----------buton pentru curentul din emitor
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'FontSize',12,...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontWeight','bold',...
'Position',[0.1 0 0.3 0.1],...
'String','Ie [mA]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0 0.3 0.1],...
'String',Ie,...
'Callback','Ie=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',Butoane_parametrii);



%-----------reprezentarea circuitului
subplot(222)
Imag= imread('imagine_proiect.jpg');
imshow(Imag);



%-----------valorile calculate a parametriilor de semnal mic
RadioGroup=uibuttongroup('Visible','on',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'Title','Parametrii de semnal mic',...
'FontWeight','bold',...
'FontSize',20,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.01 0.49 0.25 0.3]);


%-----------butoane pentru parametrii de semnal mic
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'FontWeight','bold',...
'FontSize',12,...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.0 0.3 0.2],...
'String','gm',...
'Parent',RadioGroup);

uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.5 0.1 0.3 0.1],...
'String',gm,...
'Callback','gm=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',RadioGroup);

uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontSize',12,...
'FontWeight','bold',...
'Position',[0.1 0.6 0.3 0.2],...
'String','rbe[kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.5 0.7 0.3 0.1],...
'String',rbe,...
'Parent',RadioGroup,...
'Callback','rbe=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);');

%-----------buton pentru amplificarea in tensiune
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'FontSize',12,...
'HorizontalAlignment','center',...
'Position',[0.1 0.4 0.3 0.2],...
'FontWeight','bold',...
'String','Av',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.5 0.5 0.3 0.1],...
'String',Av,...
'Callback','Av=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',RadioGroup);

%-----------buton pentru rezistenta de intrare
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'ForegroundColor','black',...
'FontWeight','bold',...
'FontSize',12,...
'HorizontalAlignment','center',...
'Position',[0.1 0.2 0.3 0.2],...
'String','Ri[kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'String',Ri,...
'Position',[0.5 0.3 0.3 0.1],...
'Callback','Ri=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',RadioGroup);

%-----------buton pentru rezistenta de iesire 
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','#FFFF00',...
'FontWeight','bold',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontSize',12,...
'Position',[0.1 0.8 0.3 0.2],...
'String','Ro[kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'Position',[ 0.5 0.9 0.3 0.1],...
'String',Ro,...
'Callback','Ro=str2num(get(gco,''string'')),close;TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
'Parent',RadioGroup);

uicontrol('Style','text',... %-----------buton pentru perioade
 'Units','normalized',...
 'Position',[0.5 0.2 0.4 0.3],...
  'FontSize',10,...
   'FontWeight','bold',...
  'BackgroundColor','#FFFF00',...
'String','Nr(perioade)',...
 'Callback','',...
 'Parent',Tip_Semnal);
   Be=uicontrol('Style','edit',...              
                'Units','normalized',... 
                 'FontSize',20,...
                  'BackgroundColor','#FFFF00',...
                'Position',[0.85 0.2 0.1 0.3],...              
                'foregroundcolor','black',...              
                'String',N,...              
                'Callback','N=str2num(get(gco,''string'')),close,TEC(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare,N,r,s,q,y,b,def);',...
                'Parent',Tip_Semnal);
  
         


%-----------reprezentarea semnalelor de intrare si de iesire---------------

switch(valoare)
    case 1                              %-----------Semnal sinusoidal------

%-----------semnalul de intrare
vi=A*sin(2*pi*f*t+def1*180/pi);
subplot(223);
plot(t,vi,'--Xg','Linewidth', 2);
title('Vi(t) - tensiunea de intrare');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------semnalul de iesire
vO=VO+Av*A*sin(2*pi*f*t+def1*180/pi);
subplot(224);
plot(t,vO,'-or','Linewidth', 2);
title('Vo(t) - tensiunea de iesire');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

    case 2                              %-----------Semnal triunghiular----

%-----------semnalul de intrare
vi=(2.*A/pi)*asin(sin(2.*pi.*f.*t+def1*180/pi));
subplot(223);
plot(t,vi,'--Xg','Linewidth', 2);
title('vi(t)');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------semnalul de iesire
vO=VO+Av.*(2.*A/pi)*asin(sin(2.*pi.*f.*t+def1*180/pi));
subplot(224);
plot(t,vO,'-or','Linewidth', 2');
title('vO');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');


    case 3                              %---------Semnal Dreptunghiular--------
%-----------semnalul de intrare
vi=A*square(2*pi*f*t+def1*180/pi);
subplot(223);
plot(t,vi,'--Xg','Linewidth', 2);
title('vi(t)');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------semnalul de iesire
vO=VO+Av*A*square(2*pi*f*t+def1*180/pi);
subplot(224);
plot(t,vO,'-or','Linewidth', 2');
title('vO');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');


    case 4                              %---------Semnal Dinte Fierastrau--------
%-----------semnalul de intrare
vi=A*sawtooth(2*pi*f*t+def1*180/pi);
subplot(223);
plot(t,vi,'--Xg','Linewidth', 2);
title('vi(t)');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------semnalul de iesire
vO=VO+Av*A*sawtooth(2*pi*f*t+def1*180/pi);
subplot(224);
plot(t,vO,'-or','Linewidth', 2');
title('vO');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');
end







%-----------buton pentru reset la valorile prestabilite 
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.92 0 0.08 .05],...
'BackgroundColor','#762659',...
'ForegroundColor','white',...
'String','Reset',...
'Callback','close;TEC(20,0.01,100,0.22,1,4.7,0.1,0.33,100,2,1,3,1,1,1,1,1,0)');


htop=0; %-----Rc
conh=0;
switch r
    case 1
        conh=1;
        htop=[0.1 0.12 0.15 0.18 0.22 0.27 0.33 0.39 0.47 0.56 0.68 0.82 1 1.2 1.5 1.8 2.2 2.7 3.3 3.9 4.7 5.6 6.8 8.2 1000 1200 1500 1800 2200 2700 3300 3900 4700 5600 6800 8200]; 

    otherwise
        conh=0;
end
conh=1;
 
marg=length(htop);
gud=0;
for i=1:marg
    if htop(i)==Rc
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.05 0.05 0.9 0.43 ],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale rezitențelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.8 0.6 0.2 0.1],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic',...
 'Parent',Butoane_parametrii); 
end


htop=0;  %------Re
conh=0;
switch s
    case 1
        conh=1;
htop=[0.1 0.12 0.15 0.18 0.22 0.27 0.33 0.39 0.47 0.56 0.68 0.82 1 1.2 1.5 1.8 2.2 2.7 3.3 3.9 4.7 5.6 6.8 8.2 1000 1200 1500 1800 2200 2700 3300 3900 4700 5600 6800 8200];
    otherwise
        conh=0;
end
conh=1;
 
marg=length(htop);
gud=0;
for i=1:marg
    if htop(i)==Re
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.05 0.05 0.9 0.43 ],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale rezitențelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.8 0.5 0.2 0.1],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic',...
 'Parent',Butoane_parametrii); 
end



htop=0;  %-----Rb1
conh=0;
switch q
    case 1
        conh=1;
htop=[0.1 0.12 0.15 0.18 0.22 0.27 0.33 0.39 0.47 0.56 0.68 0.82 1 1.2 1.5 1.8 2.2 2.7 3.3 3.9 4.7 5.6 6.8 8.2 1000 1200 1500 1800 2200 2700 3300 3900 4700 5600 6800 8200];
    otherwise
        conh=0;
end
conh=1;
 
marg=length(htop);
gud=0;
for i=1:marg
    if htop(i)==Rb1
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.05 0.05 0.9 0.43 ],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale rezitențelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.8 0.4 0.2 0.1],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic',...
 'Parent',Butoane_parametrii); 
end


htop=0;  %-----Rb2
conh=0;
switch y
    case 1
        conh=1;
htop=[0.1 0.12 0.15 0.18 0.22 0.27 0.33 0.39 0.47 0.56 0.68 0.82 1 1.2 1.5 1.8 2.2 2.7 3.3 3.9 4.7 5.6 6.8 8.2 1000 1200 1500 1800 2200 2700 3300 3900 4700 5600 6800 8200];
    otherwise
        conh=0;
end
conh=1;
 
marg=length(htop);
gud=0;
for i=1:marg
    if htop(i)==Rb2
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.05 0.05 0.9 0.43 ],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale rezitențelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.8 0.3 0.2 0.1],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic',...
 'Parent',Butoane_parametrii); 
end



htop=0;  %-----Rl
conh=0;
switch b
    case 1
        conh=1;
htop=[0.1 0.12 0.15 0.18 0.22 0.27 0.33 0.39 0.47 0.56 0.68 0.82 1 1.2 1.5 1.8 2.2 2.7 3.3 3.9 4.7 5.6 6.8 8.2 1000 1200 1500 1800 2200 2700 3300 3900 4700 5600 6800 8200];
    otherwise
        conh=0;
end
conh=1;
 
marg=length(htop);
gud=0;
for i=1:marg
    if htop(i)==Rl
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.05 0.05 0.9 0.43 ],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale rezitențelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.8 0.2 0.2 0.1],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic' ,...
 'Parent',Butoane_parametrii); 
end





fct=uimenu('Label','Documentație aferenta','Separator','on');   
 uimenu(fct,'Label','Autor si Titlu','Callback','autor_titlu');   
uimenu(fct,'Label','Prezentare power point','Callback','powerpt()');
uimenu(fct,'Label','Documentatie','Callback','documentatie()');
uimenu(fct,'Label','Bibliografie','Callback','bibliografie()');
end